/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/hchen71/slurm/lib/slurm";
char *default_slurm_config_file = "/home/hchen71/slurm/etc/slurm.conf";
char *default_plugstack = "/home/hchen71/slurm/etc/plugstack.conf";
